[[rule]]
include = ["assets/config.toml"]
schema = { path = "./schema/json/config.schema.json", enabled = true }

[[rule]]
include = ["assets/themes/*.toml"]
schema = { path = "./schema/json/theme.schema.json", enabled = true }

[[rule]]
include = ["assets/window-styles/*.toml"]
schema = { path = "./schema/json/window-style.schema.json", enabled = true }

[[rule]]
include = ["**/Cargo.toml"]

[rule.formatting]
reorder_keys = false
column_width = 160
