#:schema https://raw.githubusercontent.com/pamburus/termframe/v0.7.6/schema/json/window-style.schema.json

[window]
margin = 8

[window.border]
width = 0.5
radius = 6
colors = { outer = { dark = "#0b0f1380", light = "#545c6380" }, inner = { dark = "#ffffff40", light = "#ffffff80" } }

[window.header]
height = 24
color = { dark = "#303840", light = "#e0e0e0" }
border = { width = 0.5, color = { dark = "#00000080", light = "#40404040" } }

[window.title.color]
dark = "#b0c0c0"
light = "#586068"

[window.title.font]
family = [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "sans-serif",
]
size = 13
weight = "bold"

[window.buttons]
position = "right"
size = 16

[[window.buttons.items]]
offset = 16
icon = { kind = "close", size = 8, stroke-width = 1.5, stroke-linecap = "round", stroke = { dark = "#b0c0c0", light = "#586068" } }

[[window.buttons.items]]
offset = 34
icon = { kind = "maximize", size = 8, stroke-width = 1.5, stroke-linecap = "round", roundness = 2, stroke = { dark = "#b0c0c0", light = "#586068" } }

[[window.buttons.items]]
offset = 52
icon = { kind = "minimize", size = 8, stroke-width = 1.5, stroke-linecap = "round", stroke = { dark = "#b0c0c0", light = "#586068" } }

[window.shadow]
enabled = true
color = "#00000080"
blur = 3
x = 1
y = 1
